version: '3.8'

services:

  backend:
    build: ./example-backend
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    depends_on:
      - postgres
      - redis
    container_name: backend

  frontend:
    build: ./example-frontend
    ports:
      - 5000:5000
    depends_on:
      - backend
    container_name: frontend

  redis:
    image: redis
    container_name: redis

  postgres:
    image: postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    container_name: postgres
